### ISSUE TITLE
host.iobroker: Caught by controller[0]: Error [ERR_UNKNOWN_BUILTIN_MODULE]

### ISSUE THREAD

**Issue by TeraX** [rg-engineering/ioBroker.semp#8]
If I start the semp Instance I get follow error message in the iobroker log:

```
2022-09-10 11:19:34.279 - info: host.iobroker instance system.adapter.semp.0 started with pid 27741
--
2022-09-10 11:19:34.648 - error: host.iobroker Caught by controller[0]: internal/modules/cjs/loader.js:753
2022-09-10 11:19:34.648 - error: host.iobroker Caught by controller[0]: throw new ERR_UNKNOWN_BUILTIN_MODULE(filename);
2022-09-10 11:19:34.648 - error: host.iobroker Caught by controller[0]: ^
2022-09-10 11:19:34.648 - error: host.iobroker Caught by controller[0]: Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:stream/consumers
2022-09-10 11:19:34.648 - error: host.iobroker Caught by controller[0]: at new NodeError (internal/errors.js:322:7)
2022-09-10 11:19:34.648 - error: host.iobroker Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:753:13)
2022-09-10 11:19:34.648 - error: host.iobroker Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:974:19)
2022-09-10 11:19:34.648 - error: host.iobroker Caught by controller[0]: at require (internal/modules/cjs/helpers.js:101:18)
2022-09-10 11:19:34.649 - error: host.iobroker Caught by controller[0]: at Object. (/opt/iobroker/node_modules/iobroker.semp/lib/semp/Gateway.js:1:18)
2022-09-10 11:19:34.649 - error: host.iobroker Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:1085:14)
2022-09-10 11:19:34.649 - error: host.iobroker Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
2022-09-10 11:19:34.649 - error: host.iobroker Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:950:32)
2022-09-10 11:19:34.649 - error: host.iobroker Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:790:12)
2022-09-10 11:19:34.649 - error: host.iobroker Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:974:19) {
2022-09-10 11:19:34.649 - error: host.iobroker Caught by controller[0]: code: 'ERR_UNKNOWN_BUILTIN_MODULE'
2022-09-10 11:19:34.649 - error: host.iobroker Caught by controller[0]: }
2022-09-10 11:19:34.649 - error: host.iobroker instance system.adapter.semp.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2022-09-10 11:19:34.649 - info: host.iobroker Restart adapter system.adapter.semp.0 because enabled

```
iobroker Admin: 6.2.20
js-controller: 4.0.23
Node.js: v14.19.3
NPM: 6.14.17

I used the iobroker IP in the main settings. UUID was not generated.

![image](https://user-images.githubusercontent.com/912577/189477542-6a09a51a-9a3c-4bc5-bb69-4b39ce01a85a.png)

![image](https://user-images.githubusercontent.com/912577/189477505-41c07809-888a-4600-86c6-bebedf8bc2cb.png)

**Comment by rg-engineering** [comment]
> UUID was not generated.

If the adapter is not running, then UUID can not be generated...

so my question: how have you installed the adapter? from admin? any error messages during installation? on which OS runs your system?

**Comment by rg-engineering** [comment]
I see the same problem in continues integration (CI) tests now...

**Comment by rg-engineering** [comment]
the adapter needs node v16 or higher.
I will add a dependency...

**Comment by TeraX** [comment]
I upgraded my iobroker Instance now from:
Debian 10 ==> Debian 11
Node.js: v14.19.3 ==> v.16.17.0
NPM: 6.14.17 ==> 8.15.0

After Adding a SEMP Instance - IP and UUID was empty.
I entered manually my iobroker host IP and saved and restarted the Instance.

After that the UUID was filled in automatically.

**Comment by rg-engineering** [comment]
so I close this because #6 is still available and open
